name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Echo 'Deploying'
        run: echo 'Deploying'
