name: Documentation Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy_documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      # sphinx for documentation
      - name: Install Sphinx and dependencies
        run: |
          pip install -U sphinx sphinx-rtd-theme

      - name: Set up Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Install gh-pages
        run: npm install -g gh-pages

      - name: Build documentation
        run: |
          sphinx-build -b html docs build

      - name: Deploy documentation
        run: |
          git remote set-url origin git@github.com:drkn-123/heavens-above.git
          gh-pages -d build
        
