name: Scheduled Tasks

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday at midnight

jobs:
  maintenance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create log file
        run: echo "Hello World" > weekly-log-$(date +%Y-%m-%d).txt

      - name: Show log file content
        run: cat weekly-log-$(date +%Y-%m-%d).txt
